<?php
?>

<!DOCTYPE html>
<html>
    <head>
        <title>Astroapp Login</title>
        <link rel="stylesheet" href="/css/style.css" media="all">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script>
            let viewData = <?php $this->printViewData(); ?>
        </script>
    </head>
    <body>
        <div class="loginContainer">
            <div class="">
                <h4 id="errorMessage"></h4>
            </div>
            <img src="/img/logo.png" class="logo" alt="astro-logo">
            <form action= "../../login/attemptLogin/" class="loginForm" method="post">
                <div>
                    <label></label>
                    <input type = "text" name= "username" placeholder="Username">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "password" placeholder="Password">
                </div>
                <div>
                    <input onclick="../HomeController.php" type="submit" value="Login" class="loginButton">
                </div>
            </form>

            <form action="/account/createAccount/" class="login-form">
                <div>
                    <input class="createAccountButton" type="submit" value="Create Account">
                </div>
            </form>
            <!-- <form action="../../account/deleteAccount/">
                <input class="createAccountButton" type="submit" value="Delete Account">
            </form> -->
            <form action="../../location/setLocation/" style="visibility:visible;">
                <input id="guest" type="submit" value="Guest User">
            </form>
            <form action="../../login/logout/" style="margin-top:1em;visibility:hidden;" id="usernameDisplay" >
                <label></label>
                <input id="guest" type="submit" value="Log Out">
            </form>
        </div>
        <script>

        let errorKey = 'error';
        if( viewData.hasOwnProperty(errorKey) ) {
            document.getElementById("errorMessage").innerHTML = viewData[errorKey];
        }

        let dataKey = 'data';
        if( viewData.hasOwnProperty(dataKey) ) {
            let data = viewData['data'];
            let key = 'username';
            if( data.hasOwnProperty(key) ){
                console.log(data[key]);
                document.getElementById("usernameDisplay").setAttribute('style', 'visibility:visible');
            }

        }


        </script>
    </body>
</html>
