<?php
?>

<!DOCTYPE html>
<html>
    <head>
        <title>Astroapp Login</title>
        <link rel="stylesheet" href="/css/style.css" media="all">
        <script>
            let viewData = <?php $this->printViewData(); ?>
        </script>
    </head>
    <body>
        <div class="loginContainer">
            <div class="">
                <h4 id="errorMessage"></h4>
            </div>
            <img src="/img/logo.png" class="logo" alt="astro-logo">
            <form action= "../../login/attemptLogin/" class="loginForm" method="post">
                <div>
                    <label></label>
                    <input type = "text" name= "username" placeholder="Email">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "password" placeholder="Password">
                </div>
                <div>
                    <input onclick="../HomeController.php" type="submit" value="Login" class="loginButton">
                </div>
            </form>

            <form action="/account/createAccount/" class="login-form">
                <div>
                    <input class="createAccountButton" type="submit" value="Create Account">
                </div>
            </form>
            <form action="../../account/deleteAccount/">
                <input class="createAccountButton" type="submit" value="Delete Account">
            </form>
            <form action="../../location/setLocation/">
                <input id="guest" type="submit" value="Guest User">
            </form>
        </div>
        <script>

        let errorKey = 'error';
        if( viewData.hasOwnProperty(errorKey) ) {
            document.getElementById("errorMessage").innerHTML = viewData[errorKey];
        }
        </script>
    </body>
</html>
