<!DOCTYPE html>
<html>
    <head>
        <title>Email Already Exists</title>
        <link rel="stylesheet" href="/style.css" media="all">
    </head>
    <body>
        <div class="loginContainer">
            <img src="/logo.png" class="logo" alt = "astro-logo">
            <form action="http://localhost/account/createUserAccount/" class="loginForm" method="post">
                <div class="badEmailMessage">
                    <h3>
                        THIS EMAIL IS ALREADY IN USE. <br>
                        To reactivate your account type in your last password.
                    </h3>
                </div>               
                <div>
                    <label></label>
                    <input type = "password" name= "password" placeholder="Password">
                </div>
                <br>
                <input type="submit" value="Re-Activate Account" class="createAccountButton">
            </form>
            <form action="../../account/createAccount/">
                <input id="guest" type="submit" value="Back">
            </form>
        </div>
    </body>
</html>
