<!DOCTYPE html>
<html>
    <head>
        <title>Create Account</title>
        <link rel="stylesheet" href="/css/style.css" media="all">
    <script>
        let viewData = <?php $this->printViewData(); ?>
    </script>
    </head>
    <body>
        <div id="demo"></div>
        <div class="createAccountContainer">
            <div class="badEmailMessage">
                <h4 id="errorMessage"></h4>
            </div>
            <img src="/img/logo.png" class="logo" alt = "astro-logo">
            <form action="http://localhost/account/createUserAccount/" class="createAccountForm" method="post">
                <div>
                    <label></label>
                    <input type = "text" name= "username" placeholder="Username">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "firstName" placeholder="First Name">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "lastName" placeholder="Last Name">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "email" placeholder="Email">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "password" placeholder="Password">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "passwordConfirm" placeholder="Confirm Password">
                </div>
                <br>
                <input type="submit" value="Create Account" class="createAccountButton">
            </form>
            <form action="../../login/login/">
                <input id="guest" type="submit" value="Back">
            </form>
        </div>

        <script>

            let errorKey = 'error';
            if( viewData.hasOwnProperty(errorKey) ) {
                document.getElementById("errorMessage").innerHTML = viewData[errorKey];
            }
        </script>
    </body>
</html>