<!DOCTYPE html>
<html>
    <head>
        <title>Create Account</title>
        <link rel="stylesheet" href="/css/style.css" media="all">
    </head>
    <body>
        <div class="createAccountContainer">
            <img src="/img/logo.png" class="logo" alt = "astro-logo">
            <form action="http://localhost/account/createUserAccount/" class="createAccountForm" method="post">
                <div>
                    <label></label>
                    <input type = "text" name= "username" placeholder="Username">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "firstName" placeholder="First Name">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "lastName" placeholder="Last Name">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "email" placeholder="Email">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "password" placeholder="Password">
                </div>
                <div>
                    <label></label>
                    <input type = "password" name= "passwordConfirm" placeholder="Confirm Password">
                </div>
                <br>
                <input type="submit" value="Create Account" class="createAccountButton">
            </form>
            <form action="../../login/login/">
                <input id="guest" type="submit" value="Back">
            </form>
        </div>
    </body>
</html>