<!DOCTYPE html>
<html>
    <head>
        <title>Delete Account</title>
        <link rel="stylesheet" href="/css/style.css" media="all">
    </head>
    <body>
        <div class="loginContainer">
            <img src="/img/logo.png" class="logo" alt="astro-logo">
            <form action="http://localhost/account/deleteUserAccount/" class="loginForm" method="post">
                <div>
                    <label></label>
                    <input type = "text" name= "username" placeholder="Username">
                </div>
                <div>
                    <label></label>
                    <input type = "text" name= "password" placeholder="Password">
                </div>
                <div>
                    <input onclick="main.php" type="submit" value="DELETE ACCOUNT!" class="deleteAccountButton" method="post">
                </div>
            </form>
            <form action="../../login/login/">
                <input id="guest" type="submit" value="Back">
            </form>
    </body>
</html>